import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {once} from 'node:events';
import {LocalStore} from '../server/store.js';
import {createDemo} from '../server/demo.js';

test('state history HTTP: full catalog, guarded local transitions, review and demo sync',async t=>{
  const directory=await mkdtemp(join(tmpdir(),'neo-closing-http-')),port=14429;
  const store=new LocalStore(directory);await store.load();
  const workspace=createDemo();workspace.mode='azure';
  const rule={organization:workspace.config.organization,project:workspace.config.project,type:'Task',state:'Ready for Test',action:'include'};
  await store.save({...store.data,mode:'azure',config:workspace.config,azure:workspace,stateRules:[rule]});
  const child=spawn(process.execPath,['server/index.js'],{env:{...process.env,NEO_TEAM_PORT:String(port),NEO_TEAM_DATA_DIR:directory},stdio:['ignore','pipe','pipe']});
  t.after(async()=>{if(child.exitCode===null){child.kill();await once(child,'exit');}await rm(directory,{recursive:true,force:true});});
  await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Server did not start')),10000);child.stdout.on('data',s=>{if(s.toString().includes('Neo Team:')){clearTimeout(timer);resolve();}});child.once('exit',code=>{clearTimeout(timer);reject(new Error(`Exit ${code}`));});});
  const base=`http://127.0.0.1:${port}`;
  let state=await (await fetch(base+'/api/state')).json();
  const post=async(path,input={},version=state.version)=>{
    const response=await fetch(base+path,{method:'POST',headers:{'Content-Type':'application/json','X-Neo-CSRF':state.csrf},body:JSON.stringify({...input,version})});
    const data=await response.json();if(data.state)state=data.state;else if(data.csrf)state=data;return {status:response.status,data};
  };
  for(const file of ['settings.js']) {const res=await fetch(base+'/'+file);assert.equal(res.status,200);assert.match(res.headers.get('Content-Type'),/javascript/);}
  assert.equal(state.importRules.length,12);
  assert.equal((await post('/api/import-rule',{...rule,action:'exclude'})).status,200);
  assert.equal(state.importRules.find(r=>r.type===rule.type && r.state===rule.state).action,'exclude');
  assert.equal((await post('/api/import-rule',{...rule,project:'Another project'})).status,400);
  await post('/api/mode',{mode:'demo'});
  assert.equal(state.importRules.length,12);
  const sample={...state.importRules[0]};
  assert.equal((await post('/api/import-rule',{...sample,action:'exclude'})).status,200);
  assert.equal(state.importRules[0].action,'exclude');
  assert.equal((await post('/api/refresh-section',{section:'tasks'})).status,200);
  assert.ok(!state.workspace.items.some(item=>item.type===sample.type && item.state===sample.state));
  assert.ok(state.workspace.items.some(item=>item.type==='Bug'));
  await post('/api/import-rule',{...sample,action:'include'});
  await post('/api/refresh-section',{section:'tasks'});
  assert.ok(state.workspace.items.some(item=>item.type===sample.type && item.state===sample.state));
  await post('/api/import-rule',{...sample,action:'exclude'});
  await post('/api/mode',{mode:'azure'});
  assert.equal(state.importRules.length,12);assert.equal(state.importRules.find(r=>r.type===rule.type && r.state===rule.state).action,'exclude');
  await post('/api/mode',{mode:'demo'});
  assert.equal(state.importRules[0].action,'exclude');
  await post('/api/import-rule',{...sample,action:'include'});
  const previous=state.version;
  const catalog=await post('/api/work-item-states',{type:'Task'});
  assert.equal(catalog.status,200);assert.ok(catalog.data.states.some(s=>s.name==='Ready for Test'));
  assert.ok(state.workspace.workItemStates.Task.length);
  assert.equal((await post('/api/stage',{edits:[{id:1042,changes:{state:'Active'}}]},previous)).status,409);
  assert.equal((await post('/api/stage',{edits:[{id:1042,changes:{state:'Unknown'}}]})).status,400);
  assert.equal((await post('/api/stage',{edits:[{id:1042,changes:{state:'Ready for Test'}}]})).status,200);
  assert.equal((await post('/api/stage',{edits:[{id:1042,changes:{state:'Closed'}}]})).status,200);
  assert.deepEqual(state.workspace.stateChanges[1042],['Ready for Test','Closed']);
  const review=await post('/api/review');
  assert.deepEqual(review.data.review.plans[0].stateSteps,['Ready for Test','Closed']);
  const result=await post('/api/sync',{token:review.data.review.token});
  assert.equal(result.status,200);assert.equal(state.workspace.items.find(i=>i.id===1042).state,'Closed');
  assert.equal(state.workspace.items.find(i=>i.id===1042).rev,3);
  assert.equal(state.workspace.pendingChanges,0);
  assert.equal(state.workspace.stateChanges[1042],undefined);
});
